language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -U pipenv
  - pipenv install --dev
# command to run tests
script:
    - pipenv run python -m pytest --cov=storage --cov=core tests